

export const sample_foods: any[] = [
    {
        id:'1',
        name: 'Sancocho',
        cookTime: '60-180',
        price: 14,
        favorite: true,
        origins: ['DR'],
        stars: 5,
        imageUrl: 'assets/food-1.jpg',
        tags: ['Dinner', 'Lunch'],
  },
  {
        id:'2',
        name: 'Mangu-Tres-Golpes',
        price: 12,
        cookTime: '20-30',
        favorite: true,
        origins: ['DR'],
        stars: 4.8,
        imageUrl: 'assets/food-2.jpg',
        tags: ['Dinner', 'BreakFast'],
  },
  {
        id:'3',
        name: 'Chimi',
        price: 8,
        cookTime: '20-30',
        favorite: false,
        origins: ['DR'],
        stars: 4.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['FastFood', 'Dinner'],
  },
  {
        id:'4',
        name: 'Mofongo',
        price: 2,
        cookTime: '30-45',
        favorite: true,
        origins: ['PR', 'DR'],
        stars: 4.8,
        imageUrl: 'assets/food-4.jpg',
        tags: ['FastFood', 'Lunch', 'Dinner'],
  },
  {
        id:'5',
        name: 'Pica Pollo',
        price: 9,
        cookTime: '30',
        favorite: false,
        origins: ['China'],
        stars: 4.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['FastFood', 'Breakfast', 'Dinner'],
  },
  {
        id:'6',
        name: 'Catibia',
        price: 9,
        cookTime: '30',
        favorite: false,
        origins: ['DR'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['FastFood', 'Lunch', 'Breakfast'],
  },
]

export const sample_tags:any[] = [
      { name: 'All', count: 6},
      { name: 'FastFood', count: 4},
      { name: 'Lunch', count: 3}, 
      { name: 'Breakfast', count: 3},
      { name: 'Dinner', count: 5}, 

]